// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGXuaCMZKrz3IQNl65dqKISF1NAwIaccQ',
    appId: '1:797997951909:web:639c8de2b69f06d889564c',
    messagingSenderId: '797997951909',
    projectId: 'zera-fila',
    authDomain: 'zera-fila.firebaseapp.com',
    storageBucket: 'zera-fila.appspot.com',
    measurementId: 'G-2B2JLZB1W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7y5XLRIHvO6b5KbxR5zhmTPjKs2tN3AU',
    appId: '1:797997951909:android:839694c3623a966089564c',
    messagingSenderId: '797997951909',
    projectId: 'zera-fila',
    storageBucket: 'zera-fila.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw4pcQ0M6C9fkL9HddOgrHMOkTacdWwlw',
    appId: '1:797997951909:ios:b7606d9419443e3d89564c',
    messagingSenderId: '797997951909',
    projectId: 'zera-fila',
    storageBucket: 'zera-fila.appspot.com',
    iosClientId: '797997951909-s8g56b22vpne7j5huq6oek4ehfuudnpn.apps.googleusercontent.com',
    iosBundleId: 'com.newpointer.zeraFila',
  );
}
